#############################################################################
# Makefile for building: rtbiomanager
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  rtbiomanager.pro
# Template: app
# Command: /home/skynet/anaconda3/bin/qmake -o Makefile rtbiomanager.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -lpthread -D_GNU_SOURCE -lrt -lm -lcomedi -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../anaconda3/include/qt -I../../anaconda3/include/qt/QtWidgets -I../../anaconda3/include/qt/QtGui -I../../anaconda3/include/qt/QtCore -I. -I. -I../../anaconda3/mkspecs/linux-g++
QMAKE         = /home/skynet/anaconda3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = rtbiomanager1.0.0
DISTDIR = /home/skynet/workspace/RTBiomanager/.tmp/rtbiomanager1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/skynet/anaconda3/lib
LIBS          = $(SUBLIBS) -D_GNU_SOURCE -lrt -lm -lcomedi -L/home/skynet/anaconda3/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = gui/main.cpp \
		gui/rtbiomanager.cpp \
		clamp/src/model_library.c \
		clamp/src/rt_thread_functions.c \
		clamp/src/writer_thread_functions.c \
		clamp/src/comedi_functions.c \
		clamp/src/calibrate_functions_phase2_a.c \
		clamp/src/calibrate_functions_phase1.c \
		clamp/src/calibrate_functions_phase2.c \
		clamp/src/time_functions.c \
		clamp/src/queue_functions.c \
		clamp/src/clamp.c moc_rtbiomanager.cpp
OBJECTS       = main.o \
		rtbiomanager.o \
		model_library.o \
		rt_thread_functions.o \
		writer_thread_functions.o \
		comedi_functions.o \
		calibrate_functions_phase2_a.o \
		calibrate_functions_phase1.o \
		calibrate_functions_phase2.o \
		time_functions.o \
		queue_functions.o \
		clamp.o \
		moc_rtbiomanager.o
DIST          = ../../anaconda3/mkspecs/features/spec_pre.prf \
		../../anaconda3/mkspecs/common/unix.conf \
		../../anaconda3/mkspecs/common/linux.conf \
		../../anaconda3/mkspecs/common/sanitize.conf \
		../../anaconda3/mkspecs/common/gcc-base.conf \
		../../anaconda3/mkspecs/common/gcc-base-unix.conf \
		../../anaconda3/mkspecs/common/g++-base.conf \
		../../anaconda3/mkspecs/common/g++-unix.conf \
		../../anaconda3/mkspecs/qconfig.pri \
		../../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_clucene_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_core.pri \
		../../anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../../anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../../anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_help.pri \
		../../anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_network.pri \
		../../anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_script.pri \
		../../anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../../anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../../anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../../anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkit.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkit_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		../../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../anaconda3/mkspecs/features/qt_functions.prf \
		../../anaconda3/mkspecs/features/qt_config.prf \
		../../anaconda3/mkspecs/linux-g++/qmake.conf \
		../../anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../anaconda3/mkspecs/features/exclusive_builds.prf \
		../../anaconda3/mkspecs/features/default_pre.prf \
		../../anaconda3/mkspecs/features/resolve_config.prf \
		../../anaconda3/mkspecs/features/default_post.prf \
		../../anaconda3/mkspecs/features/warn_on.prf \
		../../anaconda3/mkspecs/features/qt.prf \
		../../anaconda3/mkspecs/features/resources.prf \
		../../anaconda3/mkspecs/features/moc.prf \
		../../anaconda3/mkspecs/features/unix/opengl.prf \
		../../anaconda3/mkspecs/features/uic.prf \
		../../anaconda3/mkspecs/features/unix/thread.prf \
		../../anaconda3/mkspecs/features/file_copies.prf \
		../../anaconda3/mkspecs/features/testcase_targets.prf \
		../../anaconda3/mkspecs/features/exceptions.prf \
		../../anaconda3/mkspecs/features/yacc.prf \
		../../anaconda3/mkspecs/features/lex.prf \
		rtbiomanager.pro gui/rtbiomanager.h \
		clamp/includes/calibrate_functions_phase1.h \
		clamp/includes/calibrate_functions_phase2.h \
		clamp/includes/calibrate_functions_phase2_a.h \
		clamp/includes/device_functions.h \
		clamp/includes/model_library.h \
		clamp/includes/queue_functions.h \
		clamp/includes/rt_thread_functions.h \
		clamp/includes/time_functions.h \
		common/includes/types.h \
		clamp/includes/writer_thread_functions.h \
		clamp/includes/clamp.h \
		clamp/includes/types_clamp.h gui/main.cpp \
		gui/rtbiomanager.cpp \
		clamp/src/model_library.c \
		clamp/src/rt_thread_functions.c \
		clamp/src/writer_thread_functions.c \
		clamp/src/comedi_functions.c \
		clamp/src/calibrate_functions_phase2_a.c \
		clamp/src/calibrate_functions_phase1.c \
		clamp/src/calibrate_functions_phase2.c \
		clamp/src/time_functions.c \
		clamp/src/queue_functions.c \
		clamp/src/clamp.c
QMAKE_TARGET  = rtbiomanager
DESTDIR       = 
TARGET        = rtbiomanager


first: all
####### Build rules

$(TARGET): ui_rtbiomanager.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: rtbiomanager.pro ../../anaconda3/mkspecs/linux-g++/qmake.conf ../../anaconda3/mkspecs/features/spec_pre.prf \
		../../anaconda3/mkspecs/common/unix.conf \
		../../anaconda3/mkspecs/common/linux.conf \
		../../anaconda3/mkspecs/common/sanitize.conf \
		../../anaconda3/mkspecs/common/gcc-base.conf \
		../../anaconda3/mkspecs/common/gcc-base-unix.conf \
		../../anaconda3/mkspecs/common/g++-base.conf \
		../../anaconda3/mkspecs/common/g++-unix.conf \
		../../anaconda3/mkspecs/qconfig.pri \
		../../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_clucene_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_core.pri \
		../../anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../../anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../../anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_help.pri \
		../../anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_network.pri \
		../../anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_script.pri \
		../../anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../../anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../../anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../../anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkit.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkit_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		../../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../anaconda3/mkspecs/features/qt_functions.prf \
		../../anaconda3/mkspecs/features/qt_config.prf \
		../../anaconda3/mkspecs/linux-g++/qmake.conf \
		../../anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../anaconda3/mkspecs/features/exclusive_builds.prf \
		../../anaconda3/mkspecs/features/default_pre.prf \
		../../anaconda3/mkspecs/features/resolve_config.prf \
		../../anaconda3/mkspecs/features/default_post.prf \
		../../anaconda3/mkspecs/features/warn_on.prf \
		../../anaconda3/mkspecs/features/qt.prf \
		../../anaconda3/mkspecs/features/resources.prf \
		../../anaconda3/mkspecs/features/moc.prf \
		../../anaconda3/mkspecs/features/unix/opengl.prf \
		../../anaconda3/mkspecs/features/uic.prf \
		../../anaconda3/mkspecs/features/unix/thread.prf \
		../../anaconda3/mkspecs/features/file_copies.prf \
		../../anaconda3/mkspecs/features/testcase_targets.prf \
		../../anaconda3/mkspecs/features/exceptions.prf \
		../../anaconda3/mkspecs/features/yacc.prf \
		../../anaconda3/mkspecs/features/lex.prf \
		rtbiomanager.pro \
		../../anaconda3/lib/libQt5Widgets.prl \
		../../anaconda3/lib/libQt5Gui.prl \
		../../anaconda3/lib/libQt5Core.prl
	$(QMAKE) -o Makefile rtbiomanager.pro
../../anaconda3/mkspecs/features/spec_pre.prf:
../../anaconda3/mkspecs/common/unix.conf:
../../anaconda3/mkspecs/common/linux.conf:
../../anaconda3/mkspecs/common/sanitize.conf:
../../anaconda3/mkspecs/common/gcc-base.conf:
../../anaconda3/mkspecs/common/gcc-base-unix.conf:
../../anaconda3/mkspecs/common/g++-base.conf:
../../anaconda3/mkspecs/common/g++-unix.conf:
../../anaconda3/mkspecs/qconfig.pri:
../../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
../../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_clucene_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
../../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_core.pri:
../../anaconda3/mkspecs/modules/qt_lib_core_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_dbus.pri:
../../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_designer.pri:
../../anaconda3/mkspecs/modules/qt_lib_designer_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_gui.pri:
../../anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_help.pri:
../../anaconda3/mkspecs/modules/qt_lib_help_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
../../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_network.pri:
../../anaconda3/mkspecs/modules/qt_lib_network_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_nfc.pri:
../../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_opengl.pri:
../../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
../../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
../../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_qml.pri:
../../anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
../../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_quick.pri:
../../anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
../../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_script.pri:
../../anaconda3/mkspecs/modules/qt_lib_script_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
../../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_sql.pri:
../../anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_svg.pri:
../../anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_testlib.pri:
../../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
../../anaconda3/mkspecs/modules/qt_lib_uitools.pri:
../../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
../../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_webkit.pri:
../../anaconda3/mkspecs/modules/qt_lib_webkit_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../anaconda3/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_websockets.pri:
../../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_widgets.pri:
../../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_x11extras.pri:
../../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_xml.pri:
../../anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../anaconda3/mkspecs/features/qt_functions.prf:
../../anaconda3/mkspecs/features/qt_config.prf:
../../anaconda3/mkspecs/linux-g++/qmake.conf:
../../anaconda3/mkspecs/features/spec_post.prf:
.qmake.stash:
../../anaconda3/mkspecs/features/exclusive_builds.prf:
../../anaconda3/mkspecs/features/default_pre.prf:
../../anaconda3/mkspecs/features/resolve_config.prf:
../../anaconda3/mkspecs/features/default_post.prf:
../../anaconda3/mkspecs/features/warn_on.prf:
../../anaconda3/mkspecs/features/qt.prf:
../../anaconda3/mkspecs/features/resources.prf:
../../anaconda3/mkspecs/features/moc.prf:
../../anaconda3/mkspecs/features/unix/opengl.prf:
../../anaconda3/mkspecs/features/uic.prf:
../../anaconda3/mkspecs/features/unix/thread.prf:
../../anaconda3/mkspecs/features/file_copies.prf:
../../anaconda3/mkspecs/features/testcase_targets.prf:
../../anaconda3/mkspecs/features/exceptions.prf:
../../anaconda3/mkspecs/features/yacc.prf:
../../anaconda3/mkspecs/features/lex.prf:
rtbiomanager.pro:
../../anaconda3/lib/libQt5Widgets.prl:
../../anaconda3/lib/libQt5Gui.prl:
../../anaconda3/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile rtbiomanager.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents gui/rtbiomanager.h clamp/includes/calibrate_functions_phase1.h clamp/includes/calibrate_functions_phase2.h clamp/includes/calibrate_functions_phase2_a.h clamp/includes/device_functions.h clamp/includes/model_library.h clamp/includes/queue_functions.h clamp/includes/rt_thread_functions.h clamp/includes/time_functions.h common/includes/types.h clamp/includes/writer_thread_functions.h clamp/includes/clamp.h clamp/includes/types_clamp.h $(DISTDIR)/
	$(COPY_FILE) --parents gui/main.cpp gui/rtbiomanager.cpp clamp/src/model_library.c clamp/src/rt_thread_functions.c clamp/src/writer_thread_functions.c clamp/src/comedi_functions.c clamp/src/calibrate_functions_phase2_a.c clamp/src/calibrate_functions_phase1.c clamp/src/calibrate_functions_phase2.c clamp/src/time_functions.c clamp/src/queue_functions.c clamp/src/clamp.c $(DISTDIR)/
	$(COPY_FILE) --parents gui/rtbiomanager.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_rtbiomanager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_rtbiomanager.cpp
moc_rtbiomanager.cpp: ../../anaconda3/include/qt/QtWidgets/QMainWindow \
		../../anaconda3/include/qt/QtWidgets/qmainwindow.h \
		../../anaconda3/include/qt/QtWidgets/qwidget.h \
		../../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../../anaconda3/include/qt/QtCore/qglobal.h \
		../../anaconda3/include/qt/QtCore/qconfig.h \
		../../anaconda3/include/qt/QtCore/qfeatures.h \
		../../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../anaconda3/include/qt/QtCore/qtypetraits.h \
		../../anaconda3/include/qt/QtCore/qisenum.h \
		../../anaconda3/include/qt/QtCore/qsysinfo.h \
		../../anaconda3/include/qt/QtCore/qlogging.h \
		../../anaconda3/include/qt/QtCore/qflags.h \
		../../anaconda3/include/qt/QtCore/qatomic.h \
		../../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../anaconda3/include/qt/QtCore/qatomic_gcc.h \
		../../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../anaconda3/include/qt/QtCore/qatomic_armv7.h \
		../../anaconda3/include/qt/QtCore/qatomic_armv6.h \
		../../anaconda3/include/qt/QtCore/qatomic_armv5.h \
		../../anaconda3/include/qt/QtCore/qatomic_ia64.h \
		../../anaconda3/include/qt/QtCore/qatomic_x86.h \
		../../anaconda3/include/qt/QtCore/qatomic_unix.h \
		../../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../anaconda3/include/qt/QtCore/qmutex.h \
		../../anaconda3/include/qt/QtCore/qnumeric.h \
		../../anaconda3/include/qt/QtCore/qversiontagging.h \
		../../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../anaconda3/include/qt/QtCore/qnamespace.h \
		../../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../../anaconda3/include/qt/QtCore/qobject.h \
		../../anaconda3/include/qt/QtCore/qstring.h \
		../../anaconda3/include/qt/QtCore/qchar.h \
		../../anaconda3/include/qt/QtCore/qbytearray.h \
		../../anaconda3/include/qt/QtCore/qrefcount.h \
		../../anaconda3/include/qt/QtCore/qarraydata.h \
		../../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../anaconda3/include/qt/QtCore/qlist.h \
		../../anaconda3/include/qt/QtCore/qalgorithms.h \
		../../anaconda3/include/qt/QtCore/qiterator.h \
		../../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../anaconda3/include/qt/QtCore/qpair.h \
		../../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../anaconda3/include/qt/QtCore/qstringlist.h \
		../../anaconda3/include/qt/QtCore/qregexp.h \
		../../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../anaconda3/include/qt/QtCore/qcoreevent.h \
		../../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../anaconda3/include/qt/QtCore/qmetatype.h \
		../../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../anaconda3/include/qt/QtCore/qobject_impl.h \
		../../anaconda3/include/qt/QtCore/qmargins.h \
		../../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../../anaconda3/include/qt/QtCore/qrect.h \
		../../anaconda3/include/qt/QtCore/qsize.h \
		../../anaconda3/include/qt/QtCore/qpoint.h \
		../../anaconda3/include/qt/QtGui/qpalette.h \
		../../anaconda3/include/qt/QtGui/qcolor.h \
		../../anaconda3/include/qt/QtGui/qrgb.h \
		../../anaconda3/include/qt/QtGui/qrgba64.h \
		../../anaconda3/include/qt/QtGui/qbrush.h \
		../../anaconda3/include/qt/QtCore/qvector.h \
		../../anaconda3/include/qt/QtGui/qmatrix.h \
		../../anaconda3/include/qt/QtGui/qpolygon.h \
		../../anaconda3/include/qt/QtGui/qregion.h \
		../../anaconda3/include/qt/QtCore/qdatastream.h \
		../../anaconda3/include/qt/QtCore/qiodevice.h \
		../../anaconda3/include/qt/QtCore/qline.h \
		../../anaconda3/include/qt/QtGui/qtransform.h \
		../../anaconda3/include/qt/QtGui/qpainterpath.h \
		../../anaconda3/include/qt/QtGui/qimage.h \
		../../anaconda3/include/qt/QtGui/qpixelformat.h \
		../../anaconda3/include/qt/QtGui/qpixmap.h \
		../../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../../anaconda3/include/qt/QtCore/qshareddata.h \
		../../anaconda3/include/qt/QtCore/qhash.h \
		../../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../../anaconda3/include/qt/QtGui/qfont.h \
		../../anaconda3/include/qt/QtGui/qfontmetrics.h \
		../../anaconda3/include/qt/QtGui/qfontinfo.h \
		../../anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../../anaconda3/include/qt/QtGui/qcursor.h \
		../../anaconda3/include/qt/QtGui/qkeysequence.h \
		../../anaconda3/include/qt/QtGui/qevent.h \
		../../anaconda3/include/qt/QtCore/qvariant.h \
		../../anaconda3/include/qt/QtCore/qmap.h \
		../../anaconda3/include/qt/QtCore/qdebug.h \
		../../anaconda3/include/qt/QtCore/qtextstream.h \
		../../anaconda3/include/qt/QtCore/qlocale.h \
		../../anaconda3/include/qt/QtCore/qset.h \
		../../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../../anaconda3/include/qt/QtCore/qurl.h \
		../../anaconda3/include/qt/QtCore/qurlquery.h \
		../../anaconda3/include/qt/QtCore/qfile.h \
		../../anaconda3/include/qt/QtCore/qfiledevice.h \
		../../anaconda3/include/qt/QtGui/qvector2d.h \
		../../anaconda3/include/qt/QtGui/qtouchdevice.h \
		../../anaconda3/include/qt/QtWidgets/qtabwidget.h \
		../../anaconda3/include/qt/QtGui/qicon.h \
		gui/rtbiomanager.h
	/home/skynet/anaconda3/bin/moc $(DEFINES) -I/home/skynet/anaconda3/mkspecs/linux-g++ -I/home/skynet/workspace/RTBiomanager -I/home/skynet/anaconda3/include/qt -I/home/skynet/anaconda3/include/qt/QtWidgets -I/home/skynet/anaconda3/include/qt/QtGui -I/home/skynet/anaconda3/include/qt/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include gui/rtbiomanager.h -o moc_rtbiomanager.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_rtbiomanager.h
compiler_uic_clean:
	-$(DEL_FILE) ui_rtbiomanager.h
ui_rtbiomanager.h: gui/rtbiomanager.ui
	/home/skynet/anaconda3/bin/uic gui/rtbiomanager.ui -o ui_rtbiomanager.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: gui/main.cpp gui/rtbiomanager.h \
		../../anaconda3/include/qt/QtWidgets/QMainWindow \
		../../anaconda3/include/qt/QtWidgets/qmainwindow.h \
		../../anaconda3/include/qt/QtWidgets/qwidget.h \
		../../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../../anaconda3/include/qt/QtCore/qglobal.h \
		../../anaconda3/include/qt/QtCore/qconfig.h \
		../../anaconda3/include/qt/QtCore/qfeatures.h \
		../../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../anaconda3/include/qt/QtCore/qtypetraits.h \
		../../anaconda3/include/qt/QtCore/qisenum.h \
		../../anaconda3/include/qt/QtCore/qsysinfo.h \
		../../anaconda3/include/qt/QtCore/qlogging.h \
		../../anaconda3/include/qt/QtCore/qflags.h \
		../../anaconda3/include/qt/QtCore/qatomic.h \
		../../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../anaconda3/include/qt/QtCore/qatomic_gcc.h \
		../../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../anaconda3/include/qt/QtCore/qatomic_armv7.h \
		../../anaconda3/include/qt/QtCore/qatomic_armv6.h \
		../../anaconda3/include/qt/QtCore/qatomic_armv5.h \
		../../anaconda3/include/qt/QtCore/qatomic_ia64.h \
		../../anaconda3/include/qt/QtCore/qatomic_x86.h \
		../../anaconda3/include/qt/QtCore/qatomic_unix.h \
		../../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../anaconda3/include/qt/QtCore/qmutex.h \
		../../anaconda3/include/qt/QtCore/qnumeric.h \
		../../anaconda3/include/qt/QtCore/qversiontagging.h \
		../../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../anaconda3/include/qt/QtCore/qnamespace.h \
		../../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../../anaconda3/include/qt/QtCore/qobject.h \
		../../anaconda3/include/qt/QtCore/qstring.h \
		../../anaconda3/include/qt/QtCore/qchar.h \
		../../anaconda3/include/qt/QtCore/qbytearray.h \
		../../anaconda3/include/qt/QtCore/qrefcount.h \
		../../anaconda3/include/qt/QtCore/qarraydata.h \
		../../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../anaconda3/include/qt/QtCore/qlist.h \
		../../anaconda3/include/qt/QtCore/qalgorithms.h \
		../../anaconda3/include/qt/QtCore/qiterator.h \
		../../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../anaconda3/include/qt/QtCore/qpair.h \
		../../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../anaconda3/include/qt/QtCore/qstringlist.h \
		../../anaconda3/include/qt/QtCore/qregexp.h \
		../../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../anaconda3/include/qt/QtCore/qcoreevent.h \
		../../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../anaconda3/include/qt/QtCore/qmetatype.h \
		../../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../anaconda3/include/qt/QtCore/qobject_impl.h \
		../../anaconda3/include/qt/QtCore/qmargins.h \
		../../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../../anaconda3/include/qt/QtCore/qrect.h \
		../../anaconda3/include/qt/QtCore/qsize.h \
		../../anaconda3/include/qt/QtCore/qpoint.h \
		../../anaconda3/include/qt/QtGui/qpalette.h \
		../../anaconda3/include/qt/QtGui/qcolor.h \
		../../anaconda3/include/qt/QtGui/qrgb.h \
		../../anaconda3/include/qt/QtGui/qrgba64.h \
		../../anaconda3/include/qt/QtGui/qbrush.h \
		../../anaconda3/include/qt/QtCore/qvector.h \
		../../anaconda3/include/qt/QtGui/qmatrix.h \
		../../anaconda3/include/qt/QtGui/qpolygon.h \
		../../anaconda3/include/qt/QtGui/qregion.h \
		../../anaconda3/include/qt/QtCore/qdatastream.h \
		../../anaconda3/include/qt/QtCore/qiodevice.h \
		../../anaconda3/include/qt/QtCore/qline.h \
		../../anaconda3/include/qt/QtGui/qtransform.h \
		../../anaconda3/include/qt/QtGui/qpainterpath.h \
		../../anaconda3/include/qt/QtGui/qimage.h \
		../../anaconda3/include/qt/QtGui/qpixelformat.h \
		../../anaconda3/include/qt/QtGui/qpixmap.h \
		../../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../../anaconda3/include/qt/QtCore/qshareddata.h \
		../../anaconda3/include/qt/QtCore/qhash.h \
		../../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../../anaconda3/include/qt/QtGui/qfont.h \
		../../anaconda3/include/qt/QtGui/qfontmetrics.h \
		../../anaconda3/include/qt/QtGui/qfontinfo.h \
		../../anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../../anaconda3/include/qt/QtGui/qcursor.h \
		../../anaconda3/include/qt/QtGui/qkeysequence.h \
		../../anaconda3/include/qt/QtGui/qevent.h \
		../../anaconda3/include/qt/QtCore/qvariant.h \
		../../anaconda3/include/qt/QtCore/qmap.h \
		../../anaconda3/include/qt/QtCore/qdebug.h \
		../../anaconda3/include/qt/QtCore/qtextstream.h \
		../../anaconda3/include/qt/QtCore/qlocale.h \
		../../anaconda3/include/qt/QtCore/qset.h \
		../../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../../anaconda3/include/qt/QtCore/qurl.h \
		../../anaconda3/include/qt/QtCore/qurlquery.h \
		../../anaconda3/include/qt/QtCore/qfile.h \
		../../anaconda3/include/qt/QtCore/qfiledevice.h \
		../../anaconda3/include/qt/QtGui/qvector2d.h \
		../../anaconda3/include/qt/QtGui/qtouchdevice.h \
		../../anaconda3/include/qt/QtWidgets/qtabwidget.h \
		../../anaconda3/include/qt/QtGui/qicon.h \
		../../anaconda3/include/qt/QtWidgets/QApplication \
		../../anaconda3/include/qt/QtWidgets/qapplication.h \
		../../anaconda3/include/qt/QtCore/qcoreapplication.h \
		../../anaconda3/include/qt/QtCore/qeventloop.h \
		../../anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		../../anaconda3/include/qt/QtGui/qguiapplication.h \
		../../anaconda3/include/qt/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o gui/main.cpp

rtbiomanager.o: gui/rtbiomanager.cpp gui/rtbiomanager.h \
		../../anaconda3/include/qt/QtWidgets/QMainWindow \
		../../anaconda3/include/qt/QtWidgets/qmainwindow.h \
		../../anaconda3/include/qt/QtWidgets/qwidget.h \
		../../anaconda3/include/qt/QtGui/qwindowdefs.h \
		../../anaconda3/include/qt/QtCore/qglobal.h \
		../../anaconda3/include/qt/QtCore/qconfig.h \
		../../anaconda3/include/qt/QtCore/qfeatures.h \
		../../anaconda3/include/qt/QtCore/qsystemdetection.h \
		../../anaconda3/include/qt/QtCore/qprocessordetection.h \
		../../anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../../anaconda3/include/qt/QtCore/qtypeinfo.h \
		../../anaconda3/include/qt/QtCore/qtypetraits.h \
		../../anaconda3/include/qt/QtCore/qisenum.h \
		../../anaconda3/include/qt/QtCore/qsysinfo.h \
		../../anaconda3/include/qt/QtCore/qlogging.h \
		../../anaconda3/include/qt/QtCore/qflags.h \
		../../anaconda3/include/qt/QtCore/qatomic.h \
		../../anaconda3/include/qt/QtCore/qbasicatomic.h \
		../../anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../../anaconda3/include/qt/QtCore/qgenericatomic.h \
		../../anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../../anaconda3/include/qt/QtCore/qatomic_gcc.h \
		../../anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../../anaconda3/include/qt/QtCore/qatomic_armv7.h \
		../../anaconda3/include/qt/QtCore/qatomic_armv6.h \
		../../anaconda3/include/qt/QtCore/qatomic_armv5.h \
		../../anaconda3/include/qt/QtCore/qatomic_ia64.h \
		../../anaconda3/include/qt/QtCore/qatomic_x86.h \
		../../anaconda3/include/qt/QtCore/qatomic_unix.h \
		../../anaconda3/include/qt/QtCore/qglobalstatic.h \
		../../anaconda3/include/qt/QtCore/qmutex.h \
		../../anaconda3/include/qt/QtCore/qnumeric.h \
		../../anaconda3/include/qt/QtCore/qversiontagging.h \
		../../anaconda3/include/qt/QtCore/qobjectdefs.h \
		../../anaconda3/include/qt/QtCore/qnamespace.h \
		../../anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../../anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../../anaconda3/include/qt/QtCore/qobject.h \
		../../anaconda3/include/qt/QtCore/qstring.h \
		../../anaconda3/include/qt/QtCore/qchar.h \
		../../anaconda3/include/qt/QtCore/qbytearray.h \
		../../anaconda3/include/qt/QtCore/qrefcount.h \
		../../anaconda3/include/qt/QtCore/qarraydata.h \
		../../anaconda3/include/qt/QtCore/qstringbuilder.h \
		../../anaconda3/include/qt/QtCore/qlist.h \
		../../anaconda3/include/qt/QtCore/qalgorithms.h \
		../../anaconda3/include/qt/QtCore/qiterator.h \
		../../anaconda3/include/qt/QtCore/qhashfunctions.h \
		../../anaconda3/include/qt/QtCore/qpair.h \
		../../anaconda3/include/qt/QtCore/qbytearraylist.h \
		../../anaconda3/include/qt/QtCore/qstringlist.h \
		../../anaconda3/include/qt/QtCore/qregexp.h \
		../../anaconda3/include/qt/QtCore/qstringmatcher.h \
		../../anaconda3/include/qt/QtCore/qcoreevent.h \
		../../anaconda3/include/qt/QtCore/qscopedpointer.h \
		../../anaconda3/include/qt/QtCore/qmetatype.h \
		../../anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../../anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../../anaconda3/include/qt/QtCore/qobject_impl.h \
		../../anaconda3/include/qt/QtCore/qmargins.h \
		../../anaconda3/include/qt/QtGui/qpaintdevice.h \
		../../anaconda3/include/qt/QtCore/qrect.h \
		../../anaconda3/include/qt/QtCore/qsize.h \
		../../anaconda3/include/qt/QtCore/qpoint.h \
		../../anaconda3/include/qt/QtGui/qpalette.h \
		../../anaconda3/include/qt/QtGui/qcolor.h \
		../../anaconda3/include/qt/QtGui/qrgb.h \
		../../anaconda3/include/qt/QtGui/qrgba64.h \
		../../anaconda3/include/qt/QtGui/qbrush.h \
		../../anaconda3/include/qt/QtCore/qvector.h \
		../../anaconda3/include/qt/QtGui/qmatrix.h \
		../../anaconda3/include/qt/QtGui/qpolygon.h \
		../../anaconda3/include/qt/QtGui/qregion.h \
		../../anaconda3/include/qt/QtCore/qdatastream.h \
		../../anaconda3/include/qt/QtCore/qiodevice.h \
		../../anaconda3/include/qt/QtCore/qline.h \
		../../anaconda3/include/qt/QtGui/qtransform.h \
		../../anaconda3/include/qt/QtGui/qpainterpath.h \
		../../anaconda3/include/qt/QtGui/qimage.h \
		../../anaconda3/include/qt/QtGui/qpixelformat.h \
		../../anaconda3/include/qt/QtGui/qpixmap.h \
		../../anaconda3/include/qt/QtCore/qsharedpointer.h \
		../../anaconda3/include/qt/QtCore/qshareddata.h \
		../../anaconda3/include/qt/QtCore/qhash.h \
		../../anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../../anaconda3/include/qt/QtGui/qfont.h \
		../../anaconda3/include/qt/QtGui/qfontmetrics.h \
		../../anaconda3/include/qt/QtGui/qfontinfo.h \
		../../anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../../anaconda3/include/qt/QtGui/qcursor.h \
		../../anaconda3/include/qt/QtGui/qkeysequence.h \
		../../anaconda3/include/qt/QtGui/qevent.h \
		../../anaconda3/include/qt/QtCore/qvariant.h \
		../../anaconda3/include/qt/QtCore/qmap.h \
		../../anaconda3/include/qt/QtCore/qdebug.h \
		../../anaconda3/include/qt/QtCore/qtextstream.h \
		../../anaconda3/include/qt/QtCore/qlocale.h \
		../../anaconda3/include/qt/QtCore/qset.h \
		../../anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../../anaconda3/include/qt/QtCore/qurl.h \
		../../anaconda3/include/qt/QtCore/qurlquery.h \
		../../anaconda3/include/qt/QtCore/qfile.h \
		../../anaconda3/include/qt/QtCore/qfiledevice.h \
		../../anaconda3/include/qt/QtGui/qvector2d.h \
		../../anaconda3/include/qt/QtGui/qtouchdevice.h \
		../../anaconda3/include/qt/QtWidgets/qtabwidget.h \
		../../anaconda3/include/qt/QtGui/qicon.h \
		ui_rtbiomanager.h \
		../../anaconda3/include/qt/QtCore/QVariant \
		../../anaconda3/include/qt/QtWidgets/QAction \
		../../anaconda3/include/qt/QtWidgets/qaction.h \
		../../anaconda3/include/qt/QtWidgets/qactiongroup.h \
		../../anaconda3/include/qt/QtWidgets/QApplication \
		../../anaconda3/include/qt/QtWidgets/qapplication.h \
		../../anaconda3/include/qt/QtCore/qcoreapplication.h \
		../../anaconda3/include/qt/QtCore/qeventloop.h \
		../../anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		../../anaconda3/include/qt/QtGui/qguiapplication.h \
		../../anaconda3/include/qt/QtGui/qinputmethod.h \
		../../anaconda3/include/qt/QtWidgets/QButtonGroup \
		../../anaconda3/include/qt/QtWidgets/qbuttongroup.h \
		../../anaconda3/include/qt/QtWidgets/QCheckBox \
		../../anaconda3/include/qt/QtWidgets/qcheckbox.h \
		../../anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		../../anaconda3/include/qt/QtWidgets/QComboBox \
		../../anaconda3/include/qt/QtWidgets/qcombobox.h \
		../../anaconda3/include/qt/QtWidgets/qabstractitemdelegate.h \
		../../anaconda3/include/qt/QtWidgets/qstyleoption.h \
		../../anaconda3/include/qt/QtWidgets/qabstractspinbox.h \
		../../anaconda3/include/qt/QtGui/qvalidator.h \
		../../anaconda3/include/qt/QtCore/qregularexpression.h \
		../../anaconda3/include/qt/QtWidgets/qslider.h \
		../../anaconda3/include/qt/QtWidgets/qabstractslider.h \
		../../anaconda3/include/qt/QtWidgets/qstyle.h \
		../../anaconda3/include/qt/QtWidgets/qtabbar.h \
		../../anaconda3/include/qt/QtWidgets/qrubberband.h \
		../../anaconda3/include/qt/QtWidgets/qframe.h \
		../../anaconda3/include/qt/QtCore/qabstractitemmodel.h \
		../../anaconda3/include/qt/QtWidgets/QDoubleSpinBox \
		../../anaconda3/include/qt/QtWidgets/qspinbox.h \
		../../anaconda3/include/qt/QtWidgets/QFrame \
		../../anaconda3/include/qt/QtWidgets/QHeaderView \
		../../anaconda3/include/qt/QtWidgets/qheaderview.h \
		../../anaconda3/include/qt/QtWidgets/qabstractitemview.h \
		../../anaconda3/include/qt/QtWidgets/qabstractscrollarea.h \
		../../anaconda3/include/qt/QtCore/qitemselectionmodel.h \
		../../anaconda3/include/qt/QtWidgets/QLabel \
		../../anaconda3/include/qt/QtWidgets/qlabel.h \
		../../anaconda3/include/qt/QtWidgets/QPlainTextEdit \
		../../anaconda3/include/qt/QtWidgets/qplaintextedit.h \
		../../anaconda3/include/qt/QtWidgets/qtextedit.h \
		../../anaconda3/include/qt/QtGui/qtextdocument.h \
		../../anaconda3/include/qt/QtGui/qtextoption.h \
		../../anaconda3/include/qt/QtGui/qtextcursor.h \
		../../anaconda3/include/qt/QtGui/qtextformat.h \
		../../anaconda3/include/qt/QtGui/qpen.h \
		../../anaconda3/include/qt/QtGui/qabstracttextdocumentlayout.h \
		../../anaconda3/include/qt/QtGui/qtextlayout.h \
		../../anaconda3/include/qt/QtGui/qglyphrun.h \
		../../anaconda3/include/qt/QtGui/qrawfont.h \
		../../anaconda3/include/qt/QtGui/qfontdatabase.h \
		../../anaconda3/include/qt/QtWidgets/QPushButton \
		../../anaconda3/include/qt/QtWidgets/qpushbutton.h \
		../../anaconda3/include/qt/QtWidgets/QSpinBox \
		../../anaconda3/include/qt/QtWidgets/QStackedWidget \
		../../anaconda3/include/qt/QtWidgets/qstackedwidget.h \
		../../anaconda3/include/qt/QtWidgets/QWidget \
		../../anaconda3/include/qt/QtWidgets/QMessageBox \
		../../anaconda3/include/qt/QtWidgets/qmessagebox.h \
		../../anaconda3/include/qt/QtWidgets/qdialog.h \
		clamp/includes/clamp.h \
		clamp/includes/rt_thread_functions.h \
		clamp/includes/time_functions.h \
		clamp/includes/model_library.h \
		clamp/includes/queue_functions.h \
		clamp/includes/types_clamp.h \
		common/includes/types.h \
		clamp/includes/calibrate_functions_phase1.h \
		clamp/includes/device_functions.h \
		clamp/includes/calibrate_functions_phase2_a.h \
		clamp/includes/calibrate_functions_phase2.h \
		clamp/includes/writer_thread_functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rtbiomanager.o gui/rtbiomanager.cpp

model_library.o: clamp/src/model_library.c clamp/includes/model_library.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o model_library.o clamp/src/model_library.c

rt_thread_functions.o: clamp/src/rt_thread_functions.c clamp/includes/rt_thread_functions.h \
		clamp/includes/time_functions.h \
		clamp/includes/model_library.h \
		clamp/includes/queue_functions.h \
		clamp/includes/types_clamp.h \
		common/includes/types.h \
		clamp/includes/calibrate_functions_phase1.h \
		clamp/includes/device_functions.h \
		clamp/includes/calibrate_functions_phase2_a.h \
		clamp/includes/calibrate_functions_phase2.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o rt_thread_functions.o clamp/src/rt_thread_functions.c

writer_thread_functions.o: clamp/src/writer_thread_functions.c clamp/includes/writer_thread_functions.h \
		clamp/includes/queue_functions.h \
		clamp/includes/types_clamp.h \
		common/includes/types.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o writer_thread_functions.o clamp/src/writer_thread_functions.c

comedi_functions.o: clamp/src/comedi_functions.c clamp/includes/device_functions.h \
		clamp/includes/types_clamp.h \
		common/includes/types.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o comedi_functions.o clamp/src/comedi_functions.c

calibrate_functions_phase2_a.o: clamp/src/calibrate_functions_phase2_a.c clamp/includes/calibrate_functions_phase2_a.h \
		clamp/includes/calibrate_functions_phase2.h \
		clamp/includes/types_clamp.h \
		common/includes/types.h \
		clamp/includes/queue_functions.h \
		clamp/includes/model_library.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o calibrate_functions_phase2_a.o clamp/src/calibrate_functions_phase2_a.c

calibrate_functions_phase1.o: clamp/src/calibrate_functions_phase1.c clamp/includes/calibrate_functions_phase1.h \
		clamp/includes/device_functions.h \
		clamp/includes/types_clamp.h \
		common/includes/types.h \
		clamp/includes/time_functions.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o calibrate_functions_phase1.o clamp/src/calibrate_functions_phase1.c

calibrate_functions_phase2.o: clamp/src/calibrate_functions_phase2.c clamp/includes/calibrate_functions_phase2.h \
		clamp/includes/types_clamp.h \
		common/includes/types.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o calibrate_functions_phase2.o clamp/src/calibrate_functions_phase2.c

time_functions.o: clamp/src/time_functions.c clamp/includes/time_functions.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o time_functions.o clamp/src/time_functions.c

queue_functions.o: clamp/src/queue_functions.c clamp/includes/queue_functions.h \
		clamp/includes/types_clamp.h \
		common/includes/types.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o queue_functions.o clamp/src/queue_functions.c

clamp.o: clamp/src/clamp.c clamp/includes/clamp.h \
		clamp/includes/rt_thread_functions.h \
		clamp/includes/time_functions.h \
		clamp/includes/model_library.h \
		clamp/includes/queue_functions.h \
		clamp/includes/types_clamp.h \
		common/includes/types.h \
		clamp/includes/calibrate_functions_phase1.h \
		clamp/includes/device_functions.h \
		clamp/includes/calibrate_functions_phase2_a.h \
		clamp/includes/calibrate_functions_phase2.h \
		clamp/includes/writer_thread_functions.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o clamp.o clamp/src/clamp.c

moc_rtbiomanager.o: moc_rtbiomanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rtbiomanager.o moc_rtbiomanager.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

